// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function handleClick(_event) {
  console.log("clicked!");
  return /* () */0;
}

function make(param) {
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  return React.createElement("div", {
              id: "root"
            }, React.createElement("p", undefined, " clicked " + (String(match[0]) + " times")), React.createElement("button", {
                  onClick: (function (_evt) {
                      return Curry._1(setCount, (function (count) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, "Click me"));
}

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
